models:
  - name: LinearRegression
    mode: fixed
    params: {}

  - name: Ridge
    mode: grid
    params:
      alpha: [0.1, 1.0, 10.0]

  - name: Lasso
    mode: grid
    params:
      alpha: [0.001, 0.01, 0.1, 1.0]

  - name: ElasticNet
    mode: sequential
    configs:
      - alpha: 0.1
        l1_ratio: 0.5

      - alpha: 1.0
        l1_ratio: 0.7

  - name: SGDRegressor
    mode: sequential
    configs:
      - loss: squared_error
        penalty: l2
        alpha: 0.0001
        max_iter: 2000

      - loss: squared_error
        penalty: elasticnet
        alpha: 0.001
        l1_ratio: 0.15
        max_iter: 2000

  - name: MLPRegressor
    mode: grid
    params:
      hidden_layer_sizes: [[32], [64, 32]]
      activation: [relu, tanh]
      solver: [adam, sgd]
      learning_rate_init: [0.001, 0.01]
      max_iter: [5000]

  - name: SVR
    mode: grid
    params:
      kernel: [linear, rbf]
      C: [1.0, 10.0, 100.0]
      epsilon: [0.1, 0.3]

  - name: KernelRidge
    mode: sequential
    configs:
      - kernel: rbf
        alpha: 1.0
        gamma: 0.1

      - kernel: polynomial
        alpha: 0.1
        degree: 3

  - name: DecisionTreeRegressor
    mode: grid
    params:
      max_depth: [3, 5, 10]
      min_samples_split: [2, 5]

  - name: RandomForestRegressor
    mode: grid
    params:
      n_estimators: [100, 200, 300]
      max_depth: [10, 20, 30]

  - name: GradientBoostingRegressor
    mode: sequential
    configs:
      - n_estimators: 100
        learning_rate: 0.1
        max_depth: 3

      - n_estimators: 200
        learning_rate: 0.05
        max_depth: 5

  - name: XGBRegressor
    mode: sequential
    configs:
      - n_estimators: 200
        learning_rate: 0.1
        max_depth: 3

      - n_estimators: 500
        learning_rate: 0.05
        max_depth: 5